version: "3.8"

# The volume is used to mount the code into the container.
# This is a must for a development environment in order to update the container
# whenever a change to the source code is made. Without this, you would have to
# re-build the image each time you make a change to the code.
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig # new
